# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UCSDDiningHallReview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UCSDDiningHallReview
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MessageInputBar'

  target 'UCSDDiningHallReviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UCSDDiningHallReviewUITests' do
    # Pods for testing
  end

end
